pipeline {
    agent {
        node {
            label 'metersphere'
        }
    }
    triggers {
        pollSCM('0 5 * * *')
    }
    environment {
        JAVA_HOME = '/opt/jdk-17'
        IMAGE_NAME = 'ui-test'
        IMAGE_PREFIX = 'registry.cn-qingdao.aliyuncs.com/metersphere'
    }
    stages {
        stage('Preparation') {
            steps {
                script {
                    REVISION = ""
                    if (env.BRANCH_NAME.startsWith("v") ) {
                        REVISION = env.BRANCH_NAME.substring(1)
                    } else {
                        REVISION = env.BRANCH_NAME
                    }
                    env.REVISION = "${REVISION}"
                    echo "REVISION=${REVISION}"
                }
            }
        }
        stage('SDK XPack Interface') {
            steps {
                sh "rm -rf frontend/.tmp_npm"
                script {
                    echo "WORKSPACE=${env.WORKSPACE}"
                    build job:"../metersphere/${BRANCH_NAME}", quietPeriod:10, parameters: [
                        string(name: 'buildSdk', value: "true"),
                        string(name: 'frontendLink', value: "${WORKSPACE}")
                    ]
                }
            }
        }
        stage('Build/Test') {
            steps {
                configFileProvider([configFile(fileId: 'metersphere-maven', targetLocation: 'settings.xml')]) {
                    sh '''#!/bin/bash -xe
                        export JAVA_HOME=/opt/jdk-17
                        export CLASSPATH=$JAVA_HOME/lib:$CLASSPATH
                        export PATH=$JAVA_HOME/bin:/opt/apache-maven-3.8.3/bin:$PATH
                        java -version
                        mvn clean package -Drevision=${REVISION} --settings ./settings.xml
                        mkdir -p backend/target/dependency && (cd backend/target/dependency; jar -xf ../*.jar;)
                    '''
                }
            }
        }
        stage('Docker build & push') {
            steps {
                sh '''#!/bin/bash -xe
                    docker --config /home/metersphere/.docker buildx build --no-cache --build-arg MS_VERSION=\${TAG_NAME:-\$BRANCH_NAME}-\${GIT_COMMIT:0:8} -t ${IMAGE_PREFIX}/${IMAGE_NAME}:\${TAG_NAME:-\$BRANCH_NAME} --platform linux/amd64,linux/arm64 . --push
                '''
            }
        }
    }
    post('Notification') {
        always {
            sh "echo \$WEBHOOK\n"
            withCredentials([string(credentialsId: 'wechat-bot-webhook', variable: 'WEBHOOK')]) {
                qyWechatNotification failNotify: true, mentionedId: '', mentionedMobile: '', webhookUrl: "$WEBHOOK"
            }
        }

    }
}
